rmanage/urls.py
from django.conf.urls import url

app_name = 'rmanage'
company_url = "r'^company/(?P<company>[A-Za-z0-9]+)"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.collab_login, name='collab_login'),
    url(r'^logout/$', views.collab_logout, name='collab_logout'),
    url(r'^company/(?P<company>[A-Za-z0-9]+)/$', views.advert, name='advert'),
    url(r'^company/(?P<company>[A-Za-z0-9]+)/apply/$', views.apply_into, name='apply_into'),
    url(r'^company/(?P<company>[A-Za-z0-9]+)/manage/$', views.manage, name='manage'),
    url(r'^company/(?P<company>[A-Za-z0-9]+)/notices/$', views.see_notices, name='see_notices'),
    url(r'^company/(?P<company>[A-Za-z0-9]+)/rdrive/(?P<r_id>(\d+))$', views.rdrive, name='rdrive'),
    url(r'^company/(?P<company>[A-Za-z0-9]+)/rdrive/(?P<r_id>(\d+))/panel$', views.rdrive, name='add_panel'),
    url(r'^company/(?P<company>[A-Za-z0-9]+)/rdrive/createnew/$', views.rdrive_create, name='rdrive_create'),
    url(r'^company/(?P<company>[A-Za-z0-9]+)/panel/$', views.panel, name='panel'),
    url(r'^company/(?P<company>[A-Za-z0-9]+)/panel/createpanel/$', views.create_panel, name='create_panel'),
    url(r'^company/(?P<company>[A-Za-z0-9]+)/addMembers/$', views.add_members, name='add_members'),
    url(r'^company/(?P<company>[A-Za-z0-9]+)/addNotice/$', views.add_notice, name='add_notice'),
    url(r'^company/(?P<company>[A-Za-z0-9]+)/candidate/$', views.view_candidates, name='view_candidates'),
    url(r'^company/(?P<company>[A-Za-z0-9]+)/rdrive/(?P<year>[0-9]+)/(?P<role>[A-Za-z0-9])/$', views.rdrive_edit, name='rdrive_edit'),
]

rportal/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^rmanage/', include('rmanage.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

rmanage/models.py
from django.contrib.auth.models import Group, User
from django.db import models


# Create your models here.


class Company(models.Model):
    name = models.CharField(max_length=100, unique=True)
    email = models.EmailField()
    password = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class RecruitmentDrive(models.Model):
    company = models.ForeignKey(Company)
    name = models.CharField(max_length=100)
    role = models.CharField(max_length=100)
    date_created = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return "%s- %s" % (self.company.name, self.name)


class Applicant(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField()
    password = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class ApplicantDetail(models.Model):
    applicant = models.ForeignKey(Applicant)
    company = models.ForeignKey(Company)
    phone_no = models.CharField(max_length=15)
    resume = models.FileField(upload_to='resume/')
    rdrive = models.ManyToManyField(RecruitmentDrive)
    role = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.applicant.name


class Round(models.Model):
    name = models.CharField(max_length=100)
    company = models.ForeignKey(Company)
    recruitment_drive = models.ForeignKey(RecruitmentDrive)
    role = models.CharField(max_length=100)

    def __str__(self):
        return "%s- %s  Round: %s" % (self.company.name,
                                      self.recruitment_drive.name, self.name)


class Panel(models.Model):
    name = models.CharField(max_length=100)
    current_candidate = models.ForeignKey(Applicant, null=True)
    rdrive = models.ForeignKey(RecruitmentDrive)
    round_info = models.ForeignKey(Round)

    def __str__(self):
        return self.name


class Collaborator(models.Model):
    hr = models.OneToOneField(User)
    company = models.ForeignKey(Company)
    panel = models.ManyToManyField(Panel)
    phone_no = models.CharField(max_length=15)

    def __str__(self):
        return self.hr.username


class CompanyAdmin(models.Model):
    admin = models.OneToOneField(User)
    company = models.ForeignKey(Company)

    def __str__(self):
        return self.company.name


class Score(models.Model):
    applicant = models.ForeignKey(Applicant)
    panel = models.ForeignKey(Panel)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.applicant.name


class Notice(models.Model):
    company = models.ForeignKey(Company)
    title = models.CharField(max_length=50)
    text = models.CharField(max_length=200)
    date_created = models.DateField()

    def __str__(self):
        return self.title

rmanage/forms.py
import django.db.models.options as options
from django import forms

from rmanage.models import *

options.DEFAULT_NAMES = options.DEFAULT_NAMES + ('fields',)


class CompanyForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = Company
        fields = ['name', 'email', 'password']


class ApplicantForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = Applicant
        fields = ['name', 'email', 'password']


class ApplicantDetailForm(forms.ModelForm):

    class Meta:
        model = ApplicantDetail
        fields = ['phone_no']


class RecruitmentDriveForm(forms.ModelForm):
    end_date = forms.DateField(widget=forms.DateInput())

    class Meta:
        model = RecruitmentDrive
        fields = ['name', 'role', 'end_date']


class RoundForm(forms.ModelForm):

    class Meta:
        model = Round
        fields = ['name', 'role']


class PanelForm(forms.ModelForm):

    class Meta:
        model = Panel
        fields = ['name', 'rdrive', 'round_info']


class CollaboratorForm(forms.ModelForm):

    class Meta:
        model = Collaborator
        fields = ['panel', 'phone_no']


class NoticeForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Notice
        fields = ['title', 'text']

rmanage/views.py
import datetime

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render

from .forms import *
from .models import *


def index(request):
    return render(request, 'rmanage/index.html', {})


def register(request):
    if request.method == 'POST':
        form = CompanyForm(request.POST)
        if form.is_valid():
            form.cleaned_data
            company = form.save(commit=False)
            company.save()
            admin = User(username=company.email)
            admin.set_password(company.password)
            admin.save()
            admin = CompanyAdmin(admin=admin, company=company)
            admin.save()
            return render(request, 'rmanage/thanks.html', {})
    else:
        form = CompanyForm()

    return render(request, 'rmanage/register.html', {'form': form})


def advert(request, company):
    if company_exists(company):
        company = Company.objects.get(name=company)
        notices = Notice.objects.filter(
            company=company).order_by('-date_created')
        return render(request, 'rmanage/advert.html', {
            'notices': notices,
            'company': company
        }
        )
    else:
        raise Http404()


def apply_into(request, company):
    if company_exists(company):
        if request.method == 'POST':
            form = ApplicantForm(request.POST)
            detailform = ApplicantDetailForm(request.POST)
            company = Company.objects.get(name=company)
            if form.is_valid() and detailform.is_valid():
                applicant = form.save(commit=False)
                applicant.save()
                applicant_detail = detailform.save(commit=False)
                applicant_detail.applicant = applicant
                applicant_detail.company = company
                applicant_detail.save()
                roles = request.POST.getlist('role')
                for r_id in roles:
                    rdrive = RecruitmentDrive.objects.get(pk=r_id)
                    applicant_detail.rdrive.add(rdrive)

                return HttpResponseRedirect('/rmanage/company/' + company.name)
        else:
            form = ApplicantForm()
            detailform = ApplicantDetailForm()
            rdrives = RecruitmentDrive.objects.filter(
                company=Company.objects.get(name=company))

        return render(request, 'rmanage/apply.html', {
            'form': form,
            'detailform': detailform,
            'company': company,
            'rdrives': rdrives
        }
        )
    else:
        raise Http404()


def manage(request, company):
    if company_auth(request, company):
        now = datetime.datetime.now()
        ongoingDrives = RecruitmentDrive.objects.filter(
            end_date__gte=now).order_by('end_date')
        previousDrives = RecruitmentDrive.objects.filter(
            end_date__lte=now).order_by('end_date')

        return render(request, 'rmanage/manage.html', {
            'ongoingDrives': ongoingDrives,
            'previousDrives': previousDrives,
            'company': company
        }
        )
    else:
        raise Http404()


def see_notices(request, company):
    if company_exists(company):
        company = Company.objects.get(name=company)
        notices = Notice.objects.filter(
            company=company).order_by('-date_created')

        return render(request, 'rmanage/notices.html', {'notices': notices})
    else:
        raise Http404()


@login_required
def rdrive(request, company, r_id):
    if company_auth(request, company):
        rdrive = RecruitmentDrive.objects.get(pk=r_id)
        rounds = Round.objects.filter(recruitment_drive=rdrive)
        panels = Panel.objects.filter(rdrive=rdrive)
        applicants = ApplicantDetail.objects.filter(rdrive=rdrive)

        return render(request, 'rmanage/rdrive_ongoing.html', {
            'rdrive': rdrive,
            'rounds': rounds,
            'panels': panels,
            'applicants': applicants
        }
        )
    else:
        raise Http404()


def rdrive_create(request, company):
    if request.method == 'POST':
        form = RecruitmentDriveForm(request.POST)
        company = company.lower()
        company = Company.objects.get(name=company)
        date_created = datetime.date.today()
        if form.is_valid():
            form.cleaned_data
            instance = form.save(commit=False)
            instance.company = company
            instance.date_created = date_created
            instance.save()
            return render(request, 'rmanage/rdrive_added.html', {})

    else:
        form = RecruitmentDriveForm()

    return render(request, 'rmanage/rdrive_create.html',
                  {'form': form, 'company': company})


@login_required
def rdrive_create(request, company):
    if is_admin(request, company):
        if request.method == 'POST':
            form = RecruitmentDriveForm(request.POST)
            company = company.lower()
            company = Company.objects.get(name=company)
            date_created = datetime.date.today()
            if form.is_valid():
                form.cleaned_data
                instance = form.save(commit=False)
                instance.company = company
                instance.date_created = date_created
                instance.save()
                return render(request, 'rmanage/rdrive_added.html', {})

        else:
            form = RecruitmentDriveForm()

        return render(request, 'rmanage/rdrive_create.html',
                      {'form': form, 'company': company})
    else:
        raise Http404()


def rdrive_round(request, company, r_id):
    if is_admin(request, company):
        if request.method == 'POST':
            form = RoundForm(request.POST)
            if form.is_valid():
                form.cleaned_data
                instance = form.save(commit=False)
                instance.company = Company.objects.get(name=company)
                instance.recruitment_drive = RecruitmentDrive.objects.get(
                    pk=r_id)
    else:
        raise Http404()


@login_required
def panel(request, company):
    if company_auth(request, company):
        return HttpResponse("View Panel")


def add_panel(request, company, r_id):
    return HttpResponse("Welcome to Panel Page")


@login_required
def create_panel(request, company):
    if is_admin(request, company):
        return HttpResponse("Create a panel")


@login_required
def add_members(request, company):
    if is_admin(request, company):
        return HttpResponse("Add collaborators")
    else:
        raise Http404()


@login_required
def add_notice(request, company):
    if is_admin(request, company):
        if request.method == "POST":
            form = NoticeForm(request.POST)
            if form.is_valid():
                form.cleaned_data
                notice = form.save(commit=False)
                notice.company = Company.objects.get(name=company)
                notice.date_created = datetime.date.today()
                notice.save()
                return HttpResponseRedirect(
                    '/rmanage/company/' + company + '/manage/')
        else:
            form = NoticeForm()

        return render(request, 'rmanage/add_notice.html', {'form': form})
    else:
        raise Http404()


@login_required
def view_candidates(request, company):
    if company_auth(request, company):
        return HttpResponse("View Candidate")
    else:
        raise Http404()


@login_required
def rdrive_edit(request, company):
    if is_admin(request, company):
        return HttpResponse("Edit Recruitment Drive")


def collab_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                try:
                    company = CompanyAdmin.objects.get(admin=user).company.name
                except:
                    company = Collaborator.objects.get(hr=user).company.name
                manage_url = '/rmanage/company/' + company + '/manage/'
                return HttpResponseRedirect(manage_url)
        else:
            return render(request, 'rmanage/login.html', {
                'error_message': 'Invalid Credentials'
            })
    else:
        return render(request, 'rmanage/login.html', {})


@login_required
def collab_logout(request):
    logout(request)
    return HttpResponseRedirect('/rmanage/')


@login_required
def company_auth(request, company):
    user = request.user
    company = Company.objects.get(name=company)
    if Collaborator.objects.filter(hr=user, company=company).exists() or \
            CompanyAdmin.objects.filter(admin=user, company=company).exists():
        return True
    else:
        return False


def company_exists(company):
    if Company.objects.filter(name=company).exists():
        return True
    else:
        return False


def is_admin(request, company):
    user = request.user
    company = Company.objects.get(name=company)
    if CompanyAdmin.objects.filter(admin=user, company=company).exists():
        return True
    else:
        return False

rmanage/templates/rmanage/add_notice.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Add Notice</title>
        <meta charset="UTF-8">
    </head>
    <body>
        <form action="." method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit"/>
        </form>
    </body>
</html>                   

rmanage/templates/rmanage/advert.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{{ company }}</title>
    </head>
    <body>
        <h1>Notices</h1>
        {% for notice in notices %}
            <div class='notice'>
                <b>{{notice.title}}</b><br>
                {{ notice.text }}
            </div>
        {% endfor %}
        <a href="/rmanage/company/{{ company }}/apply"><button id="apply">Apply now</button></a>
        {% if request.user.is_authenticated %}
        <a href="/rmanage/company/{{ company }}/manage"><button id="manage">Manage</button></a>
        {% endif %}
    </body>
</html>

rmanage/templates/rmanage/apply.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Apply into company</title>
    </head>
    <body>
        <form action="/rmanage/company/{{company}}/apply/" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            {{ detailform.as_p }}
            Role:
            {% for rdrive in rdrives %}
            <input type="checkbox" name="role" value="{{rdrive.id}}">{{ rdrive.name }}</input>
            {% endfor %}
            <br><br>
            <input type="submit" value="Submit"/>
        </form>
    </body>
</html>

rmanage/templates/rmanage/front.html
<html>
	<head>
		<link rel="stylesheet" href="index.css">
	</head>
	<body>
		<div class="header">
			<div class="name">
				<div class="app">
					RPORTAL
				</div>
				<div class="tagline">
					India Works Digitally		
				</div>
			</div>
		</div>
		<div>
			<div class="info">
				yoyo here comes the theme	
			</div>	
			<div>
				<center>
					<button>
						LOGIN	
					</button>
					&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
					&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
					<button>
						SIGN UP
					</button>
				</center>
			</div>
		</div>
	</body>
</html>

rmanage/templates/rmanage/index.html
{% extends "base.html"  %}
{% block title  %} Welcome  {% endblock  %}

{% block head %}
        <title>RManage</title>
        <meta charset="UTF-8">
{% endblock %}
{% block content %}
        <div class='container'> 
             <div class='row'>
                 <div class= 'col-lg-6 col-lg-offset-3'>
                     <div class = 'home_head'>
                         Welcome to ManagHR
                     </div> 
                 <div>
             </div>
             <div class='row'>
                 <div class = 'col-lg-8 col-lg-offset-2'>
                       </hr stlye='width:100%; height:5px'>
                 </div>
             </div>
             <div class='row'>
                 <div class = 'col-lg-10 col-lg-offser-1'>
                      <div class = 'home_subhead'>
                         Your one stop solution to all your hiring needs
                      </div>
                 </div>
             </div>
             <div class='row'>
                 <div class= 'col-lg-5 col-lg-offset-3'>
                     <a href="/rmanage/register"><button class='home_button' id="register">Apply now</button></a>
                     <a href="/rmanage/login"><button class='home_button' id="login">Login</button></a>                     
                 </div>
             </div>
        </div>
{% endblock %}

rmanage/templates/rmanage/login.html
{% extends 'base.html' %}
{% block title  %} Login {% endblock %}
{% block content %}
      <div class='container'>
         <div class='row'>
             <div class='col-lg-6 col-lg-offset-3'>
                 <div class='register_form'>
                     <div class='register_text'>
                        <center> Sign in to your existing account</center>
                     </div>
                     <center>
                         <form action='/rmanage/login/' method="post">
                             {% csrf_token %}
                             <div class="form-group">
				<label for="sel1">Username:</label> <input type="text" name="username" id="sel1"/><br>
                             </div>    
			     <div class="form-group">
				<label for="sel2">Password:</label> <input type="password" name="password" id="sel2"/><br>
                             </div>
				<input type="submit" value="Submit" class="btn"/>
                             {{ error_message }}
                         </form> 
                    </center>                
                  </div>
             </div>
    </div>
   
{% endblock %} 
  

rmanage/templates/rmanage/manage.html
{% extends 'base.html' %}

{% block title  %} Manage {% endblock  %}

{% block content %}
    <div class= 'container'>
        <div style="font-size:30px">Manage Your Recruitment </div>
        <div class='well'>
            <a href="{% url 'rmanage:rdrive_create' company  %}">Create a New Recruitment Drive</a></br></br>
        </div>
        <div class='well'>
            Ongoing Recruitment Drives
            <br>
            {% for drive in ongoingDrives %}
            <a href="{% url 'rmanage:rdrive' drive.company.name drive.id  %}">{{ drive.name }}</a>
            {% endfor %}
            </br></br>
        </div>
       <div class='well'>
            Previous Recruitment Drives
            </br>
            {% for drive in previousDrives %}
            {{ drive.name  }}
            {% endfor  %}
        </div>
         <div class='well'>
             Other Links
            <a href="{% url 'rmanage:add_members' company %}">Add HR Managers</a>
            <a href="{% url 'rmanage:add_notice' company %}">Add Notices</a>
        </div>
 
    </div>
{% endblock  %}

rmanage/templates/rmanage/rdrive.html
Welcome to Recruitment Drive Page.

Name of Recuitment Drive: {{rdrive.name}}</br>
</br>
Rounds in the given recuitment drive are</br>
{% for round in rounds  %}
{{round.name}}
{% endfor %}
</br></br>

<a href="{% url 'rmanage:add_panel' rdrive.company.name rdrive.id  %}">Add Another Round </a>
 

rmanage/templates/rmanage/rdrive_added.html
Drive Successfully Added

rmanage/templates/rmanage/rdrive_create.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Add Recruitment Drive</title>
        <meta charset="UTF-8">
    </head>
    <body>
        <form action="." method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit"/>
        </form>
    </body>
</html>

rmanage/templates/rmanage/rdrive_ongoing.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Rdrive</title>
        <meta charset="UTF-8">
    </head>
    <body>
        <h1>{{rdrive.name}}</h1>
        <div class="round">
            {% for round in rounds %}
                {{ round.name }} : {{ round.role }}
            {% endfor %}
            <a href="#">Add round</a>
        </div>
        <div class="panel">
            {% for panel in panels %}
                {{ panel.name }}
                Current candidate: {{ panel.current_candidate.name }}
                Round: {{ panel.round_info.name }}
            {% endfor %}
            <a href="#">Add Panel</a>
        </div>
        <div class="applicants">
            Applicants:
            {% for applicant in applicants %}
                Name: {{ applicant.applicant.name }}
            {% endfor %}
        </div>
    </body>
</html>

rmanage/templates/rmanage/register.html
{% extends "base.html"  %}
{% block title %}
   Register
{% endblock %}
{% block head %}
   <meta charset="UTF-8">
{% endblock %}
{% block content  %}
     <div class='container'>
         <div class='row'>
             <div class='col-lg-6 col-lg-offset-3'>
                 <div class='register_form'>
                     <div class='register_text'>
                        <center> Register for a new account</center>
                     </div>
                     <center>
                     <form class='reg_form' action="/rmanage/register/" method="post">
                         {% csrf_token %}
                         {{ form.as_p }}
                         <input type="submit" value="Submit"/>
                     </form>
                     </center>                
                  </div>
             </div>
    </div>
{% endblock %}

rmanage/templates/rmanage/thanks.html
Thanks for registering.
 